# pretrained model is already saved in checkpoints_save1, so we can evaluate it directly.
python runner9_NS_transformer.py \
        --not_training \
        --model_id 'Evaluate_electricity_diffusion_step_100' \
        --model 'Evaluate_electricity_diffusion_step_100' \
        --pretrained_model_path 'checkpoints/Electricity_96_192_Electricity_96_192_custom_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/checkpoint.pth' \
        --pretrained_cond_model_path 'checkpoints/Electricity_96_192_Electricity_96_192_custom_ftM_sl96_ll48_pl192_dm512_nh8_el2_dl1_df2048_fc3_ebtimeF_dtTrue_Exp_0/best_cond_model_dir/checkpoint.pth' \
        --gpu '4' \
        --root_path './dataset/electricity' \
        --data_path 'electricity.csv' \
        --seq_len 96 \
        --label_len 48 \
        --pred_len 192 \
        --features 'M' \
        --n_heads 8 \
        --enc_in '321' \
        --dec_in '321' \
        --c_out '321' \
        --diffusion_steps '100' \
        --timesteps '100' \
        --test_batch_size '4' \